### ISSUE TITLE
segfault when directly calling a method from python

### ISSUE THREAD

**Issue by ryanmrichard** [pulsar-chem/Pulsar-Core#33]
It's simple to work around, but if you try something like:

```.py
import pulsar as psr
from systems.water_dimer import make_system  #I forgot to change the name in master...
with psr.ModuleAdministrator() as mm:
     #Assume you have standard modules installed
    mm.load_module("pulsar_modules","Bondizer","PSR_BOND_FRAG")
    my_sys=make_system()
    frags=mm.get_module("PSR_BOND_FRAG",0).fragmentize(my_sys)
```

you get a segfault because the module pointer gets released and `fragmentize` is called on a null pointer.  The work around is to save the module to a variable and then call the instance's method.

**Comment by bennybp** [comment]
Good find. I think I see the problem. It has to do with the way the python smart pointers return their internal functions in `__getattr__`. Let me think of a good fix

**Comment by bennybp** [comment]
See if the fix in branch issue33 fixes the problem. I've also added a test for it (which we should do for issues like this).

If it fixes it, go ahead and merge it

**Comment by ryanmrichard** [comment]
Fix works for me.  I think the test for the issue is fine for the moment, but I think it would be better to put it as a test item in another test which ensures the functions of a returned module all work.
